### ISSUE TITLE
Reordering column causes missing alters on other columns

### ISSUE THREAD

**Issue by azarecki** [skeema/skeema#36]
Hello, :)

I stumbled upon some issues with verifyDiff on `skeema diff` with a lot of alters and column reordering. I think I narrowed my problem down to a simplified example. I had a table:

> CREATE TABLE `test` (
>   `id` int NOT NULL,
>   `b` int DEFAULT NULL,
>   `c` tinyint DEFAULT NULL,
>   `a` int DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

I wanted to move `a` column under `id` and change type of `c` to int, so I changed the schema file accordingly:

> CREATE TABLE `test` (
>   `id` int NOT NULL,
>   `a` int DEFAULT NULL,
>   `b` int DEFAULT NULL,
>   `c` int DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Next, I run `skeema diff` to get a list of alters and following error occurred:

> 2018-08-21 23:34:55 [ERROR] verifyDiff: Failure on table test
> DDL:
> [ALTER TABLE `test` ALGORITHM=COPY, MODIFY COLUMN `a` int(11) DEFAULT NULL AFTER `id`]
> 
> EXPECTED POST-ALTER:
> CREATE TABLE `test` (
>   `id` int(11) NOT NULL,
>   `a` int(11) DEFAULT NULL,
>   `b` int(11) DEFAULT NULL,
>   `c` int(11) DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8
> 
> ACTUAL POST-ALTER:
> CREATE TABLE `test` (
>   `id` int(11) NOT NULL,
>   `a` int(11) DEFAULT NULL,
>   `b` int(11) DEFAULT NULL,
>   `c` tinyint(4) DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8

There is no column `c` type change in ALTER statement, so the check is correct, database schema will not be correct after this statement. 

Please advice, am I missing something? This issue blocks me from using skeema in my project.

Thanks in advance :)

**Comment by evanelias** [comment]
Thank you for the excellent issue report! I've reproduced this, and verified that it's a bug. Seems there's a logic problem in the code for this specific situation (one col is moved and another is changed)... the column reordering code is a bit tricky due to the number of possible permutations it needs to handle. Hope to have a fix, along with new test-case coverage, later this week.

**Comment by evanelias** [comment]
Fixed in master yesterday in 18bf68f, and included in today's new release, [Skeema v1.0.4](https://github.com/skeema/skeema/releases/tag/v1.0.4). Thanks again for the thorough bug report!

**Comment by azarecki** [comment]
Thank you again, my issue is solved with the new release. :)

**Comment by azarecki** [comment]
Unfortunately, I still have some issues with column reordering. I prepared an example:
I had a table: 

> CREATE TABLE `test` (
>   `a` int(11) unsigned NOT NULL AUTO_INCREMENT,
>   `d` int(10) NOT NULL,
>   `b` int(10) unsigned DEFAULT 0,
>   `e` int(10) unsigned DEFAULT NULL,
>   `c` int(10) unsigned NOT NULL,
>   PRIMARY KEY (`a`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> 

I wanted to move the `d` column and make some changes to column types, so I changed the schema file accordingly:

> CREATE TABLE `test` (
>   `a` int(11) unsigned NOT NULL AUTO_INCREMENT,
>   `b` bigint(20) DEFAULT NULL,
>   `c` bigint(20) DEFAULT NULL,
>   `d` int(10) NOT NULL,
>   `e` bigint(20) DEFAULT NULL,
>   PRIMARY KEY (`a`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Next, I run `skeema diff` to get a list of alters and following error occurred:

> `2018-09-03 13:35:58 [ERROR] Error 1054: Unknown column 'd' in 'test'`

I saw that on DB there is following query executed:

> ALTER TABLE `test` ALGORITHM=COPY, MODIFY COLUMN `d` int(10) NOT NULL AFTER `e`, MODIFY COLUMN `e` bigint(20) DEFAULT NULL AFTER `c`, MODIFY COLUMN `d` int(10) NOT NULL AFTER `c`, MODIFY COLUMN `b` bigint(20) DEFAULT NULL, MODIFY COLUMN `c` bigint(20) DEFAULT NULL

As you can see there are two different `MODIFY COLUMN` on column `d`. If you try to execute the same query on DB there is same error.

@evanelias can you replicate this issue? Thanks in advance. :)

**Comment by evanelias** [comment]
The new issue is now fixed in 4b4815c2b46fe, and included in today's new release, [Skeema v1.0.5](https://github.com/skeema/skeema/releases/tag/v1.0.5).

Thanks again for the issue reports, and my apologies for the repeated problems relating to column reordering. I believe the column reordering logic is finally 100% solid now with the new algorithm. I ran some comprehensive tests which included many iterations of randomly-generated column reorderings (and other column changes randomly mixed in), and the tests now pass on all supported versions of MySQL, MariaDB, and Percona Server.
